version: '3'
networks:
  web:
    external: true
volumes:
  node_modules:
services:
  web:
    build: .
    env_file: .env
    restart: always
    stdin_open: true
    tty: true
    command: ${COMMAND}
    environment:
      TZ: 'America/Sao_Paulo'
    networks:
      - web
    volumes:
      - node_modules:/app/node_modules
      - ${VOLUME_WEB}:/app
    ports:
      - '3000:3000'
